---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: api-proxy
  name: belugapps-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: api-proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api-proxy
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: TRUENAS_URL
              valueFrom:
                secretKeyRef:
                  key: host
                  name: truenas-creds
            - name: TRUENAS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: api-token
                  name: truenas-creds
          image: gcr.io/belug-apps/api-proxy:{{ .belug-apps.version }}
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          name: proxy
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 150m
              memory: 150Mi
            requests:
              cpu: 20m
              memory: 150Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      securityContext:
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: api-proxy
spec:
  ports:
    - port: 80
      targetPort: http
