---
name: Lint (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/**/*"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f  # tag=v3.3.1
        with:
          go-version: 1.19
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3.3.1
        with:
          version: latest
          working-directory: ./src/api-proxy

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: github/codeql-action/init@bab5a146ac6d7a082c88e24391b2b1fc4ac67ec0  # tag=codeql-bundle-20221024
        with:
          languages: go
      - uses: github/codeql-action/autobuild@bab5a146ac6d7a082c88e24391b2b1fc4ac67ec0  # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@bab5a146ac6d7a082c88e24391b2b1fc4ac67ec0  # tag=codeql-bundle-20221024
