---
name: Lint (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/**/*"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f  # tag=v3.3.1
        with:
          go-version: 1.19
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3.3.1
        with:
          version: latest
          working-directory: ./src/api-proxy

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: github/codeql-action/init@def4f60c6c6b7cbc80e88f5972238e77096403db  # tag=codeql-bundle-20221024
        with:
          languages: go
      - uses: github/codeql-action/autobuild@def4f60c6c6b7cbc80e88f5972238e77096403db  # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@def4f60c6c6b7cbc80e88f5972238e77096403db  # tag=codeql-bundle-20221024
