---
name: Lint (NodeJS/Typescript)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/kubeapps-components/**/*"]

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: github/codeql-action/init@4fddc51e4f3b5e5e9022f35c3464736cc10e1e98  # tag=codeql-bundle-20221024
        with:
          languages: javascript
      - uses: github/codeql-action/autobuild@4fddc51e4f3b5e5e9022f35c3464736cc10e1e98  # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@4fddc51e4f3b5e5e9022f35c3464736cc10e1e98  # tag=codeql-bundle-20221024
