---
name: Lint (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.go", "**/go.sum", "**/go.mod"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f  # tag=v3.3.1
        with:
          go-version: 1.19
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1  # tag=v3.3.0
        with:
          version: latest
          working-directory: ./api-proxy

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: github/codeql-action/init@f0a12816612c7306b485a22cb164feb43c6df818  # tag=codeql-bundle-20221024
        with:
          languages: go
      - uses: github/codeql-action/autobuild@f0a12816612c7306b485a22cb164feb43c6df818  # tag=codeql-bundle-20221024
      - uses: github/codeql-action/analyze@f0a12816612c7306b485a22cb164feb43c6df818  # tag=codeql-bundle-20221024
