---
name: Lint (Golang)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.go", "**/go.sum", "**/go.mod"]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      # yamllint disable-line rule:line-length
      - uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
        with:
          version: latest
          working-directory: ./api-proxy

  codeql:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - uses: github/codeql-action/init@40542d38bc4936c2ca7da883aeb050a6081b4b31
        with:
          languages: go
      # yamllint disable-line rule:line-length
      - uses: github/codeql-action/autobuild@40542d38bc4936c2ca7da883aeb050a6081b4b31
      # yamllint disable-line rule:line-length
      - uses: github/codeql-action/analyze@40542d38bc4936c2ca7da883aeb050a6081b4b31
