---
name: Security (Helm Charts)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["charts/**"]
  push:
    branches: [main]

jobs:
  check_helm_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # tag=v1.5.0
        continue-on-error: true
        with:
          find_vulnerabilities: true
          iac_dir: charts
          iac_type: helm
          iac_version: v3
          sarif_upload: true
      - uses: github/codeql-action/upload-sarif@def4f60c6c6b7cbc80e88f5972238e77096403db # tag=codeql-bundle-20221024
        with:
          sarif_file: terrascan.sarif
