---
name: Security (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["src/api-proxy/**/*"]
  push:
    branches: [main]

jobs:
  check_golang_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: snyk/actions/golang@7fad562681122205233d1242c3bb39598c5393da # tag=0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif src/api-proxy/
      - uses: github/codeql-action/upload-sarif@def4f60c6c6b7cbc80e88f5972238e77096403db # tag=codeql-bundle-20221024
        with:
          sarif_file: snyk.sarif
