---
name: Security (Helm Charts)
on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["charts/**"]

jobs:
  check_helm_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: tenable/terrascan-action@dd7e921056c6f25b25bff3cf791e063ed7fc3a78 # tag=v1.5.0
        continue-on-error: true
        with:
          find_vulnerabilities: true
          iac_dir: charts
          iac_type: helm
          iac_version: v3
          sarif_upload: true
      - uses: github/codeql-action/upload-sarif@4fddc51e4f3b5e5e9022f35c3464736cc10e1e98 # tag=codeql-bundle-20221024
        with:
          sarif_file: terrascan.sarif
