---
name: Test (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.go", "**/go.sum", "**/go.mod"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
        working-directory: ./api-proxy
      - run: ls api-proxy
      - uses: codecov/codecov-action@e0fbd592d323cb2991fb586fdd260734fcb41fcb
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: api-proxy/coverage.txt
          flags: unittests
