---
name: Test (Golang)
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize]
    paths: ["**.go", "**/go.sum", "**/go.mod"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
        with:
          go-version: 1.19
      - uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic
        working-directory: ./api-proxy
      - run: ls api-proxy
      - uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: api-proxy/coverage.txt
          flags: unittests
